version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: yu_picture_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: yu_picture
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docs/mysql/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:7-alpine
    container_name: yu_picture_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass 123456

volumes:
  mysql_data:
  redis_data: